== Guides / Testing

元ネタ: link:https://hono.dev/docs/guides/testing[Hono / Guides / Testing]

疑問がある。

{BRANCH_URL}/packages/testing/src/sample.test.ts[] にこういうtestを書いた。このtestは実行するとPASSする。

- link:{BRANCH_URL}/packages/testing/src/sample.test.ts[]

[source,typescript]
----
include::../packages/testing/src/sample.test.ts[lines=45..56]
----

ここで `http://localhost/posts` というURLを指定している。

`http` プロトコルじゃなくて `https` を指定し、別のhostnameや別のport番号を指定したらどうなるだろう。つまりURLの形式には適合的だが、対応するHTTPサーバの実物が存在しないURLを指定したらどうなるか。例えばこんなふうに：

[source,typescript]
----
include::../packages/testing/src/sample.test.ts[lines=57..68]
----

なんと、これもPASSした！

```
$ bun run test:testinghono
$ bun test --cwd ./packages/testinghono
bun test v1.3.6 (d530ed99)

src/sample.test.ts:
✓ Example > GET /posts [0.46ms]
✓ Example > POST /posts [0.91ms]
✓ Example > POST /posts with JSON data [0.11ms]
✓ Example > POST /posts with multipart/form-data [0.34ms]
✓ Example > POST /posts using Request class [0.11ms]
✓ Example > POST /posts using Request class with curious hostname and port [0.06ms]

 6 pass
 0 fail
 17 expect() calls
Ran 6 tests across 1 file. [13.00ms]
```

後者のtestがPASSしたという事実から推測するに、Requestクラスのコンストラクタの第一引数として指定したURL文字列の protocol と hostname と port を `app.request(url, )` が無視している。

そうなのか？

[source,typescript]
----
...
        const req = new Request('https://127.1.2.3:8080/posts', { method: 'POST' })
        const res = await app.request(req)
...
----

このコードにおて appオブジェクトのrequestメソッドが `https://127.1.2.3:8080` を無視して `/post` を抜き出して利用するならば、それは

[source,typescript]
----
...
        const res = await app.request('/posts', { method: 'POST' })
...
----

と同じだ。そう理解することもできる。

さらに考えを進めてみよう。sample.test.tsの69行目にこういうtestを書いた。

[source,typescript]
----
include::../packages/testing/src/sample.test.ts[lines=69..80]
----

これもPASSした。new Hono()が代入されたappは `protocol://hostname:9999/posts` という出鱈目なURLを受けとっても平気だ。URLのpath部分つまり `/posts` という箇所だけを参照して HTTPステータス 201 を応答した。

続けて81行目にこういうテストを書いた。

[source,typescript]
----
include::../packages/testing/src/sample.test.ts[lines=81..88]
----

URLのpathを `/postzzz` にした。このpathは実在しない。appは `/postzzz` を受け付けるように作られていない。だから404 Not Found を応答した。

なるほど。腑に落ちた感じがする。
